# SPDX-License-Identifier: GPL-3.0-or-later
"""RIB 3.1-flavored export for RetroMan's translated Blender scene.

This intentionally exports the public RenderMan-style scene model, not any Pixar
private extensions. It is also the textual interchange format planned for
RetroMan's own future RIB reader.
"""
import math
from pathlib import Path

import bpy
from bpy_extras.io_utils import ExportHelper
from bpy.props import StringProperty
from mathutils import Vector

from .scene_adapter import extract_scene


class _ExportEngine:
    def test_break(self):
        return False

    def update_progress(self, value):
        pass


def _fmt(x):
    return f"{float(x):.9g}"


def _vec(v):
    return " ".join(_fmt(x) for x in v)


def _matrix_rib(matrix):
    # Blender uses column-vector math while classic RIB matrices are commonly
    # written in row-vector convention. Transpose for a useful interchange form.
    m = matrix.transposed()
    return " ".join(_fmt(m[r][c]) for r in range(4) for c in range(4))


def _quoted(text):
    return '"' + str(text).replace('\\', '\\\\').replace('"', '\\"') + '"'


def _camera_fov(camera):
    try:
        y = float(camera.projection[1][1])
        if abs(y) > 1.0e-8:
            return math.degrees(2.0 * math.atan(1.0 / abs(y)))
    except Exception:
        pass
    return 45.0


def _light_direction(light):
    local = Vector((0.0, 0.0, 1.0)) if light.type == "SUN" else Vector((0.0, 0.0, -1.0))
    d = light.matrix_world.to_3x3() @ local
    return d.normalized() if d.length_squared > 1.0e-12 else Vector((0.0, 0.0, -1.0))


def write_rib(rscene, filepath):
    path = Path(filepath)
    path.parent.mkdir(parents=True, exist_ok=True)
    s = rscene.settings
    lines = []
    lines.append("##RenderMan RIB-Structure 1.1")
    lines.append("version 3.03")
    lines.append("# Generated by RetroMan 1.0.4 from an evaluated Blender scene")
    lines.append(f'Format {rscene.width} {rscene.height} 1')
    ps = max(1, int(getattr(s, 'pixel_samples', 2)))
    lines.append(f'PixelSamples {ps} {ps}')
    lines.append(f'ShadingRate {_fmt(getattr(s, "shading_rate", 4.0))}')
    pf = {'BOX':'box','GAUSSIAN':'gaussian','MITCHELL':'catmull-rom'}.get(str(getattr(s, 'pixel_filter', 'GAUSSIAN')).upper(), 'gaussian')
    lines.append(f'PixelFilter "{pf}" 2 2')
    lines.append('Display "RetroMan.tif" "file" "rgba"')
    try:
        is_ortho = abs(float(rscene.camera.projection[3][3]) - 1.0) < 1.0e-5
    except Exception:
        is_ortho = False
    if is_ortho:
        lines.append('Projection "orthographic"')
    else:
        lines.append(f'Projection "perspective" "fov" [{_fmt(_camera_fov(rscene.camera))}]')
    lines.append(f'Transform [{_matrix_rib(rscene.camera.matrix_world.inverted())}]')
    lines.append("")
    lines.append("WorldBegin")

    wc = rscene.world_color
    ambient = max(0.0, float(getattr(s, "ambient", 0.12)))
    lines.append(
        f'  LightSource "ambientlight" 1 "intensity" [{_fmt(ambient)}] '
        f'"lightcolor" [{_vec(wc)}]'
    )

    light_id = 2
    for light in rscene.lights:
        c = light.color
        pos = light.matrix_world.translation
        if light.type == "SUN":
            d = _light_direction(light)
            lines.append(
                f'  LightSource "distantlight" {light_id} "intensity" [{_fmt(light.energy)}] '
                f'"lightcolor" [{_vec(c)}] "from" [0 0 0] "to" [{_vec(d)}]'
            )
        elif light.type == "SPOT":
            d = _light_direction(light)
            to = pos + d
            cone = max(0.001, float(light.spot_size) * 0.5)
            delta = cone * max(0.001, float(light.spot_blend))
            lines.append(
                f'  LightSource "spotlight" {light_id} "intensity" [{_fmt(light.energy)}] '
                f'"lightcolor" [{_vec(c)}] "from" [{_vec(pos)}] "to" [{_vec(to)}] '
                f'"coneangle" [{_fmt(cone)}] "conedeltaangle" [{_fmt(delta)}]'
            )
        else:
            lines.append(
                f'  LightSource "pointlight" {light_id} "intensity" [{_fmt(light.energy)}] '
                f'"lightcolor" [{_vec(c)}] "from" [{_vec(pos)}]'
            )
        if light.use_shadow:
            lines.append(f"  # RetroMan auto-shadow-map light: {light.name}")
        light_id += 1

    if rscene.environment_texture is not None:
        tex = rscene.environment_texture
        lines.append(f"  # World Environment Texture: {tex.name}")
        if tex.filepath:
            lines.append(f"  # Source image: {tex.filepath}")
        lines.append("  # RetroMan samples this as a 1995-style latitude/longitude environment map.")

    lines.append("")
    for i, tri in enumerate(rscene.triangles):
        m = tri.material
        lines.append("  AttributeBegin")
        lines.append(f"    # triangle {i} material {_quoted(m.name)}")
        lines.append(f"    Color [{_vec(m.base_color[:3])}]")
        lines.append(f"    Opacity [{_fmt(m.alpha)} {_fmt(m.alpha)} {_fmt(m.alpha)}]")
        if m.metallic >= 0.5:
            lines.append(
                f'    Surface "metal" "Ka" [{_fmt(max(0.0, getattr(m, "ka", 1.0)))}] "Ks" [{_fmt(max(0.0, getattr(m, "ks", m.specular)))}] '
                f'"roughness" [{_fmt(max(0.001, m.roughness))}]'
            )
        else:
            lines.append(
                f'    Surface "plastic" "Ka" [{_fmt(max(0.0, getattr(m, "ka", 1.0)))}] "Kd" [{_fmt(max(0.0, getattr(m, "kd", 1.0 - m.metallic)))}] '
                f'"Ks" [{_fmt(max(0.0, getattr(m, "ks", m.specular)))}] "roughness" [{_fmt(max(0.001, m.roughness))}]'
            )
        if m.texture is not None:
            lines.append(f"    # Base image texture: {m.texture.name} ({m.texture.filepath or 'packed/generated'})")
        if getattr(m, "normal_texture", None) is not None:
            lines.append(f"    # Normal map: {m.normal_texture.name} strength={_fmt(m.normal_strength)}")
        if getattr(m, "bump_texture", None) is not None:
            lines.append(f"    # Bump map: {m.bump_texture.name} strength={_fmt(m.bump_strength)} distance={_fmt(m.bump_distance)}")
        if getattr(m, "retrosl_source", ""):
            lines.append("    # RetroSL override active")
        if getattr(m, "kr", -1.0) >= 0.0:
            lines.append(f"    # Kr reflection coefficient [{_fmt(m.kr)}]")
        if m.has_displacement:
            lines.append(
                f"    # Micropolygon displacement: scale={_fmt(m.displacement_scale)} "
                f"midlevel={_fmt(m.displacement_midlevel)}"
            )
        P = list(tri.a.p) + list(tri.b.p) + list(tri.c.p)
        N = list(tri.a.n) + list(tri.b.n) + list(tri.c.n)
        st = list(tri.a.uv) + list(tri.b.uv) + list(tri.c.uv)
        lines.append(f'    Polygon "P" [{_vec(P)}] "N" [{_vec(N)}] "st" [{_vec(st)}]')
        lines.append("  AttributeEnd")

    lines.append("WorldEnd")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


class RETROMAN_OT_export_rib(bpy.types.Operator, ExportHelper):
    bl_idname = "retroman.export_rib"
    bl_label = "Export RetroMan RIB"
    bl_description = "Export the evaluated Blender scene as a RenderMan 3.1-style RIB file"
    filename_ext = ".rib"
    filter_glob: StringProperty(default="*.rib", options={"HIDDEN"})

    def execute(self, context):
        try:
            depsgraph = context.evaluated_depsgraph_get()
            rscene, warnings = extract_scene(depsgraph, _ExportEngine())
            write_rib(rscene, self.filepath)
            for warning in warnings[:8]:
                self.report({"WARNING"}, warning)
            self.report({"INFO"}, f"RetroMan RIB exported: {self.filepath}")
            return {"FINISHED"}
        except Exception as exc:
            self.report({"ERROR"}, f"RIB export failed: {exc}")
            return {"CANCELLED"}
